---
image: docker:git

services:
  - docker:dind

include:
  # https://docs.gitlab.com/ee/user/application_security/container_scanning/
  - template: Container-Scanning.gitlab-ci.yml
  # https://docs.gitlab.com/ee/user/application_security/secret_detection/
  - template: Secret-Detection.gitlab-ci.yml
  # Own Template
  - https://gitlab.com/it-bgk/gitlab-templates/-/raw/master/shellcheck.yml
  # License Scanning
  - template: Security/License-Scanning.gitlab-ci.yml

stages:
  - build
  - test
  - release

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  RELEASE_CI_REGISTRY: ""
  #
  #DOCKER_USERNAME
  #DOCKER_PASSWORD
  #
  #CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  #CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  CORTEX_CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CORTEX_CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  THEHIVE_CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  THEHIVE_CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  MISP_MODULES_CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  MISP_MODULES_CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  # For Container Scanning
  CLAIR_OUTPUT: High

before_script:
  # Login to Gitlab Docker Registry
  - echo "$CI_JOB_TOKEN" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  # Login to hub.docker.com Registry
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin 
  # Save Version to file (will be read by api.py)
  - echo "$CI_COMMIT_REF_NAME BUILD ${CI_COMMIT_SHA:0:8}" > .version
  - git clone https://gitlab.com/it-bgk/helper-scripts.git /helper_scripts
  - /helper_scripts/add_tag_2_.vars.sh docker-compose.yml elasticsearch-oss TAG_ES

build-test-misp-modules:
  stage: build
  script:
    - git clone https://github.com/MISP/misp-modules.git
    - cd misp-modules
    - docker build --pull -t $MISP_MODULES_CONTAINER_TEST_IMAGE docker/
    - docker push $MISP_MODULES_CONTAINER_TEST_IMAGE
  except:
    - master

build-test-cortex:
  stage: build
  script:
    - docker build --pull -t $CORTEX_CONTAINER_TEST_IMAGE .docker/cortex
    - docker push $CORTEX_CONTAINER_TEST_IMAGE
  except:
    - master

build-test-thehive:
  stage: build
  script:
    - docker build --pull -t $THEHIVE_CONTAINER_TEST_IMAGE .docker/thehive4
    - docker push $THEHIVE_CONTAINER_TEST_IMAGE
  except:
    - master

# test:
#   stage: test
#   script:
#     - docker pull $CONTAINER_TEST_IMAGE
#     - docker run $CONTAINER_TEST_IMAGE /script/to/run/another/test
#   except:
#     - master

# build-release-cortex:
#   stage: release
#   script:
#     - docker pull $CORTEX_CONTAINER_TEST_IMAGE
#     - docker tag $CORTEX_CONTAINER_TEST_IMAGE $CORTEX_CONTAINER_RELEASE_IMAGE
#     - docker push $CORTEX_CONTAINER_RELEASE_IMAGE
#   only:
#     - master

# build-release-thehive:
#   stage: release
#   script:
#     - docker pull $THEHIVE_CONTAINER_TEST_IMAGE
#     - docker tag $THEHIVE_CONTAINER_TEST_IMAGE $THEHIVE_CONTAINER_RELEASE_IMAGE
#     - docker push $THEHIVE_CONTAINER_RELEASE_IMAGE
#   only:
#     - master

retag-elasticsearch:
  stage: build
  script:
    - source .vars
    - docker pull docker.elastic.co/elasticsearch/elasticsearch-oss:${TAG_ES}
    - docker tag docker.elastic.co/elasticsearch/elasticsearch-oss:${TAG_ES} itbgk/elasticsearch-oss:${TAG_ES}
    - docker push itbgk/elasticsearch-oss:${TAG_ES}
  # only:
  #   - master
