---
image: docker:git

services:
  - docker:dind

include:
  # https://docs.gitlab.com/ee/user/application_security/container_scanning/
  - template: Container-Scanning.gitlab-ci.yml
  # https://docs.gitlab.com/ee/user/application_security/secret_detection/
  - template: Secret-Detection.gitlab-ci.yml
  # Own Template
  - https://gitlab.com/it-bgk/gitlab-templates/-/raw/master/shellcheck.yml
  # License Scanning
  - template: Security/License-Scanning.gitlab-ci.yml

stages:
  - build
  - test
  - release

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  RELEASE_CI_REGISTRY: ""
  #
  #DOCKER_USERNAME
  #DOCKER_PASSWORD
  #
  #CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  #CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  CORTEX_CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/cortex:$CI_COMMIT_REF_SLUG
  CORTEX_CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/cortex:latest
  THEHIVE_CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/thehive:$CI_COMMIT_REF_SLUG
  THEHIVE_CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/thehive:latest
  MISP_MODULES_CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/misp-modules:$CI_COMMIT_REF_SLUG
  MISP_MODULES_CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/misp-modules:latest
  # For Container Scanning
  CLAIR_OUTPUT: High

before_script:
  # Login to Gitlab Docker Registry
  - echo "$CI_JOB_TOKEN" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  # Save Version to file (will be read by api.py)
  - echo "$CI_COMMIT_REF_NAME BUILD ${CI_COMMIT_SHA:0:8}" > .version
  - git clone https://gitlab.com/it-bgk/helper-scripts.git /helper_scripts
  - /helper_scripts/add_tag_2_.vars.sh docker-compose.yml elasticsearch-oss TAG_ES
  - curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
  - curl -L "https://github.com/christian-korneck/docker-pushrm/releases/download/v1.7.0/docker-pushrm_linux_amd64" -o /usr/local/bin/docker-pushrm && chmod +x /usr/local/bin/docker-pushrm
  
container_scanning:
  before_script:
   - echo ""

license_scanning:
  before_script:
   - echo ""

secret_detection_default_branch :
  before_script:
   - echo ""

###############

build-test-misp-modules:
  stage: build
  script:
    - git clone https://github.com/MISP/misp-modules.git
    - cd misp-modules
    - git checkout $BRANCH
    - docker build --pull -t $MISP_MODULES_CONTAINER_TEST_IMAGE docker/
    - docker push $MISP_MODULES_CONTAINER_TEST_IMAGE
  parallel:
    matrix:
      - BRANCH: 
          - master
          - 2.4.121


build-test-cortex:
  stage: build
  script:
    - docker build --pull --build-arg VERSION=$VERSION -t $CORTEX_CONTAINER_TEST_IMAGE .docker/cortex
    - docker push $CORTEX_CONTAINER_TEST_IMAGE
  parallel:
    matrix:
      - VERSION: 3.1.0-1

build-test-thehive:
  stage: build
  script:
    - docker build --pull --build-arg VERSION=$VERSION -t $THEHIVE_CONTAINER_TEST_IMAGE .docker/thehive4
    - docker push $THEHIVE_CONTAINER_TEST_IMAGE
  parallel:
    matrix:
      - VERSION: 4.0.1-1
      - VERSION: 4.0.2-1


# test:
#   stage: test
#   script:
#     - docker pull $CONTAINER_TEST_IMAGE
#     - docker run $CONTAINER_TEST_IMAGE /script/to/run/another/test
#   except:
#     - master

build-release-cortex:
  stage: release
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin 
    - docker pull $CORTEX_CONTAINER_TEST_IMAGE
    - docker tag $CORTEX_CONTAINER_TEST_IMAGE $CORTEX_CONTAINER_RELEASE_IMAGE
    - docker push $CORTEX_CONTAINER_RELEASE_IMAGE
    - docker run --rm -v $PWD/.docker/cortex:/workspace -e DOCKERHUB_REPOSITORY='$CORTEX_CONTAINER_RELEASE_IMAGE' -e DOCKERHUB_USERNAME='$DOCKER_USERNAME' -e DOCKERHUB_PASSWORD='$DOCKER_PASSWORD' -e README_FILEPATH='/workspace/README.md' peterevans/dockerhub-description:2.1.0
  only:
    - master

build-release-thehive:
  stage: release
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin 
    - docker pull $THEHIVE_CONTAINER_TEST_IMAGE
    - docker tag $THEHIVE_CONTAINER_TEST_IMAGE $THEHIVE_CONTAINER_RELEASE_IMAGE
    - docker push $THEHIVE_CONTAINER_RELEASE_IMAGE
    - docker run --rm -v $PWD/.docker/thehive:/workspace -e DOCKERHUB_REPOSITORY='$THEHIVE_CONTAINER_RELEASE_IMAGE' -e DOCKERHUB_USERNAME='$DOCKER_USERNAME' -e DOCKERHUB_PASSWORD='$DOCKER_PASSWORD' -e README_FILEPATH='/workspace/README.md' peterevans/dockerhub-description:2.1.0
  only:
    - master

build-release-misp-modules:
  stage: release
  script:
    - git clone https://github.com/MISP/misp-modules.git
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin 
    - docker pull $MISP_MODULES_CONTAINER_TEST_IMAGE
    - docker tag $MISP_MODULES_CONTAINER_TEST_IMAGE $MISP_MODULES_CONTAINER_RELEASE_IMAGE
    - docker push $MISP_MODULES_CONTAINER_RELEASE_IMAGE
    - docker run --rm -v $PWD/misp-modules:/workspace -e DOCKERHUB_REPOSITORY='$MISP_MODULES_CONTAINER_RELEASE_IMAGE' -e DOCKERHUB_USERNAME='$DOCKER_USERNAME' -e DOCKERHUB_PASSWORD='$DOCKER_PASSWORD' -e README_FILEPATH='/workspace/README.md' peterevans/dockerhub-description:2.1.0
  only:
    - master

retag-release-elasticsearch:
  stage: release
  script:
    - source .vars
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin 
    - docker pull docker.elastic.co/elasticsearch/elasticsearch-oss:${TAG_ES}
    - docker tag docker.elastic.co/elasticsearch/elasticsearch-oss:${TAG_ES} itbgk/elasticsearch-oss:${TAG_ES}
    - docker push itbgk/elasticsearch-oss:${TAG_ES}
    - docker run --rm -v $PWD/.docker/elasticsearch:/workspace -e DOCKERHUB_REPOSITORY='itbgk/elasticsearch-oss' -e DOCKERHUB_USERNAME='$DOCKER_USERNAME' -e DOCKERHUB_PASSWORD='$DOCKER_PASSWORD' -e README_FILEPATH='/workspace/README.md' peterevans/dockerhub-description:2.1.0
  only:
    - master
