version: '2.4'

volumes:
    es_data:
        name: es_data
    es_config:
        name: es_config
    cassandra_data:
        name: cassandra_data
    minemeld_local:
        name: minemeld_local
    minemeld_logs:
        name: minemeld_logs

networks:
    egress:
        name: egress
        ipam:
            driver: default
            config:
                - subnet: "${EGRESS_IP_SUBNET}.0/27"
        driver_opts:
            com.docker.network.bridge.name: docker-egress0
    traefik_internal:
        name: traefik_internal
        internal: true
        ipam:
            driver: default
            config:
                - subnet: "${INTERNAL_IP_SUBNET}.0/27"
        driver_opts:
            com.docker.network.bridge.name: docker-traefik0
    docker_proxy_internal:
        name: docker_proxy_internal
        internal: true
        ipam:
            driver: default
            config:
                - subnet: "${DOCKER_PROXY_IP_SUBNET:-192.168.240}.0/24"
        driver_opts:
            com.docker.network.bridge.name: docker-proxy0
            
services:
    docker-socket-proxy:
        image: tecnativa/docker-socket-proxy
        restart: unless-stopped
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
          - CONTAINERS=10
          - INFO=1
        networks:
          docker_proxy_internal:
            ipv4_address: "${DOCKER_PROXY_IP_SUBNET:-192.168.240}.2"
        runtime: runc
        mem_limit: 32M
    ###
    filebeat:
        image: itbgk/filebeat:7.12.0-file
        container_name: central-filebeat
        hostname: ${FQDN:-${HOSTNAME}}
        restart: unless-stopped
        networks:
          docker_proxy_internal:
            ipv4_address: "${DOCKER_PROXY_IP_SUBNET:-192.168.240}.3"
          default:
        volumes:
        - /var/lib/docker/containers/:/var/lib/docker/containers:ro
        - /var/log:/var/log:ro
        - /var/log/filebeat:/var/log/filebeat
        extra_hosts: 
          - "docker-socket-proxy:${DOCKER_PROXY_IP_SUBNET:-192.168.240}.2"
        mem_limit: 64M
        group_add:
        - adm
    ###
    elasticsearch:
        image: itbgk/elasticsearch-oss:7.9.2
        restart: unless-stopped
        container_name: elasticsearch
        networks:
            traefik_internal:
        environment: 
            - node.name=elasticsearch
            - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
            - "http.host=0.0.0.0"
            - "discovery.type=single-node"
            - "transport.host=0.0.0.0"
            - script.allowed_types=inline
            - thread_pool.search.queue_size=100000
            - thread_pool.write.queue_size=10000
            - path.repo=/backup
            - cluster.name=hive
            #- opendistro_security.ssl.http.enabled=false  
        expose:
            - 9200 # HTTP
        volumes:
            - es_data:/usr/share/elasticsearch/data
            - es_config:/usr/share/elasticsearch/config
            #- ./DATA/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./BACKUP/elasticsearch:/backup
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        mem_limit: 6G
    ###
    cortex:
        image: itbgk/cortex:${CORTEX_VERSION}
        build:
            context: .docker/cortex
            args: 
                VERSION: ${CORTEX_VERSION}
        restart: unless-stopped
        container_name: cortex
        volumes:
            #- ./DATA/cortex/application.conf:/etc/cortex/application.conf
            - /var/run/docker.sock:/var/run/docker.sock:ro # https://github.com/TheHive-Project/Cortex/issues/260#issuecomment-673292919
            - es_config:/es_config:ro
            #- ./DATA/cortex/nslr:/opt/cortex/nslr:ro
            - /tmp/cortex-jobs:/tmp/cortex-jobs
        environment: 
            - SECRET=${CORTEX_SECRET}
            - AUTH=${CORTEX_AUTH:-local}
            - AUTH_AD_DOMAINFQDN=${CORTEX_AUTH_AD_DOMAINFQDN}
            - AUTH_AD_SERVERNAMES=${CORTEX_AUTH_AD_SERVERNAMES}
            - AUTH_AD_DOMAINNAME=${CORTEX_AUTH_AD_DOMAINNAME}
            - AUTH_LDAP_SERVER=${CORTEX_AUTH_LDAP_SERVER}
            - AUTH_LDAP_BIND_DN=${CORTEX_AUTH_LDAP_BIND_DN}
            - AUTH_LDAP_BIND_PASSWORD=${CORTEX_AUTH_LDAP_BIND_PASSWORD}
            - AUTH_LDAP_BASE_DN=${CORTEX_AUTH_LDAP_BASE_DN}
            - AUTH_LDAP_FILTER=${CORTEX_AUTH_LDAP_FILTER}
            - ES_HOSTNAME=${CORTEX_ES_HOSTNAME}
            - ES_URI=${CORTEX_ES_URL:-http://elasticsearch:9200}
            - ES_AUTH_USER=${CORTEX_ES_AUTH_USER}
            - ES_AUTH_PW=${CORTEX_ES_AUTH_PW}
            - CONFIG_FILE=${CORTEX_CONFIG_FILE}
            - DOCKER_HOST=${CORTEX_DOCKER_HOST}
            - DOCKER_GID=${CORTEX_DOCKER_GID} # Set the correct local docker group GID
            - JOB_DIRECTORY=${CORTEX_JOB_DIRECTORY}
            - DEBUG=${CORTEX_DEBUG}
            # - JAVA_OPTS=-Djavax.net.ssl.trustStore=/etc/thehive/truststore/truststore.jks
        networks:
            egress:
            traefik_internal:
        depends_on:
        - elasticsearch
        expose:
            - 9001
        mem_limit: 2G
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.cortex.rule=Host(`cortex.${FQDN}`)"
            - "traefik.http.services.cortex.loadbalancer.server.port=9001"
            - "traefik.http.routers.cortex.entrypoints=https"
            - "traefik.http.routers.cortex.middlewares=internal-ip"
    ###
    thehive:
        image: itbgk/thehive4:${TH_VERSION}
        build:
            context: .docker/thehive4
            args: 
                VERSION: ${TH_VERSION}
        restart: unless-stopped
        container_name: thehive
        networks:
            egress:
            traefik_internal:
        #volumes:
            #- ./DATA/thehive/application_4.conf:/etc/thehive/application.conf
        depends_on:
        - cassandra
        - elasticsearch
        environment: 
            # https://github.com/TheHive-Project/TheHiveDocs/blob/master/installation/install-guide.md#customize-the-docker-image
            - AUTH_AD_WINDOMAIN=${TH_AUTH_AD_WINDOMAIN}
            - AUTH_AD_DNSDOMAIN=${TH_AUTH_AD_DNSDOMAIN}
            - AUTH_AD_USESSL=${TH_AUTH_AD_USESSL:-false}
            - AUTH_AD_HOSTS=${TH_AUTH_AD_HOSTS}
            - AUTH_DEFAULTUSERDOMAIN=${TH_AUTH_DEFAULTUSERDOMAIN}
            - CASSANDRA_DB_HOSTNAME=${TH_CASSANDRA_DB_HOSTNAME:-th-cassandra}
            - CORTEX_KEY=${TH_CORTEX_KEY}
            - CORTEX_URL=${TH_CORTEX_URL:-http://cortex:9001}
            - DEBUG=${TH_DEBUG}
            - MISP_INT_URL=${TH_MISP_INT_URL:-http://misp-internal/}
            - MISP_INT_KEY=${TH_MISP_INT_KEY}
            - MISP_INT_CASE_TEMPLATE=${TH_MISP_INT_CASE_TEMPLATE}
            - MISP_INT_MAX_AGE=${TH_MISP_INT_MAX_AGE:-7 days}
            - MISP_INT_EXCLUDE_ORGS=${TH_MISP_INT_EXCLUDE_ORGS}
            - MISP_INT_EXCLUDE_TAGS=${TH_MISP_INT_EXCLUDE_TAGS}
            - MISP_INT_WHITELIST_TAGS=${TH_MISP_INT_WHITELIST_TAGS}
            - MISP_PUB_URL=${TH_MISP_PUB_URL:-http://misp-public/}
            - MISP_PUB_KEY=${TH_MISP_PUB_KEY}
            - MISP_PUB_CASE_TEMPLATE=${TH_MISP_PUB_CASE_TEMPLATE}
            - MISP_PUB_MAX_AGE=${TH_MISP_PUB_MAX_AGE:-"7 days"}
            - MISP_PUB_EXCLUDE_ORGS=${TH_MISP_PUB_EXCLUDE_ORGS}
            - MISP_PUB_EXCLUDE_TAGS=${TH_MISP_PUB_EXCLUDE_TAGS}
            - MISP_PUB_WHITELIST_TAGS=${TH_MISP_PUB_WHITELIST_TAGS}
            - SECRET=${TH_SECRET}
            - ELASTICSEARCH_HOSTS=${TH_ELASTICSEARCH_HOSTS:-http://elasticsearch:9200}
        expose:
            - 9000
        mem_limit: 2G
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.thehive.rule=Host(`case.${FQDN}`,`${FQDN}`,`thehive.${FQDN}`)"
            - "traefik.http.services.thehive.loadbalancer.server.port=9000"
            - "traefik.http.routers.thehive.entrypoints=https"
            - "traefik.http.routers.thehive.middlewares=internal-ip"
    ###
    cassandra:
        image: cassandra:latest
        restart: unless-stopped
        container_name: th-cassandra
        volumes: 
            - cassandra_data:/var/lib/cassandra
        networks: 
            traefik_internal:
        healthcheck:
            test: ["CMD", "cqlsh -e 'describe cluster'|| exit 1"]
            interval: 30s
            timeout: 30s
            retries: 3
            start_period: 60s
        mem_limit: 2G
    ###
    minemeld:
        image: paloaltonetworks/minemeld
        container_name: minemeld
        restart: unless-stopped
        tmpfs: /run
        environment: 
            - REQUESTS_CA_BUNDLE=/opt/minemeld/local/certs/cacert.pem
        volumes: 
            - minemeld_local:/opt/minemeld/local
            - minemeld_logs:/opt/minemeld/log
            # https://live.paloaltonetworks.com/t5/minemeld-discussions/minemeld-outbound-calls-impacted-by-ssl-interception/m-p/133152#M642
            - ${SSL_ROOT_CA}:/opt/minemeld/local/certs/site/custom-root-ca:ro
        networks:
            egress:
            traefik_internal:
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.minemeld.rule=Host(`minemeld.${FQDN}`)"
            - "traefik.http.services.minemeld.loadbalancer.server.port=443"
            - "traefik.http.services.minemeld.loadbalancer.server.scheme=https"
            - "traefik.http.routers.minemeld.entrypoints=https"
            - "traefik.http.routers.minemeld.middlewares=internal-ip"
    ###
    nginx:
        image: nginx:stable-alpine
        restart: unless-stopped
        container_name: nginx-static-files
        volumes:
        - ./DATA/nginx-static-files/:/usr/share/nginx/html/:ro
        networks: 
            traefik_internal:
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nginx-static-files.rule=Host(`s.${FQDN}`)"
            - "traefik.http.services.nginx-static-files.loadbalancer.server.port=80"
            - "traefik.http.routers.nginx-static-files.middlewares=internal-ip"
    ###