version: "3.3"
networks:
    traefik_internal:
        external: true
        
services:
    watcher:
        networks: 
            traefik_internal:
            default:
        ports:
        - 127.0.0.1:60000:9002
        #environment: 
            #- CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
        volumes: 
            - ${SSL_ROOT_CA}:/etc/ssl/certs/custom-root-ca.crt:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.watcher.rule=Host(`watcher.${FQDN}`)"
            - "traefik.http.routers.watcher.entrypoints=https"
            - "traefik.http.services.watcher.loadbalancer.server.port=9002"
    rss-bridge:
        #environment: 
            #- CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
        volumes:
            - ${BASE_FOLDER}/../../DATA/watcher/rss-bridge/whitelist.txt:/app/whitelist.txt
            - ${SSL_ROOT_CA}:/etc/ssl/certs/custom-root-ca.crt:ro
    searx:
        #environment: 
            #- CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
        volumes:
            - ${BASE_FOLDER}/../../DATA/watcher/searx/searx:/etc/searx:rw
            - ${SSL_ROOT_CA}:/etc/ssl/certs/custom-root-ca.crt:ro
