#!/usr/bin/with-contenv bash
source /default_vars.sh

exec s6-setuidgid cortex \
/opt/cortex/bin/cortex \
	-Dconfig.file="$CONFIG_FILE" \
	-Dlogger.file=/etc/cortex/logback.xml \
	-Dpidfile.path=/dev/null \
	"$@"
