#!/bin/sh
DEBUG=${DEBUG:-"0"}
[ $DEBUG -eq 0 ] || set -x

CASSANDRA_DB_HOSTNAME=${CASSANDRA_DB_HOSTNAME:-"th-cassandra"}
CONFIG_FILE=${CONFIG_FILE:-"/etc/thehive/application.conf"}
CONFIG=${CONFIG:-"1"}
SECRET="${SECRET:-"$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)"}"

CORTEX_URL=${CORTEX_URL}
CORTEX_KEY=${CORTEX_KEY}
MISP_URL=${MISP_URL}
MISP_KEY=${MISP_KEY}
MISP_CASE_TEMPLATE=${MISP_CASE_TEMPLATE}
AUTH_AD_DNSDOMAIN=${AUTH_AD_DNSDOMAIN}
AUTH_AD_HOSTS=${AUTH_AD_HOSTS}
AUTH_AD_WINDOMAIN=${AUTH_AD_WINDOMAIN}
AUTH_LDAP_SERVER=${AUTH_LDAP_SERVER}
AUTH_LDAP_BIND_DN=${AUTH_LDAP_BIND_DN}
AUTH_LDAP_BIND_PASSWORD=${AUTH_LDAP_BIND_PASSWORD}
AUTH_LDAP_BASE_DN=${AUTH_LDAP_BASE_DN}
AUTH_LDAP_FILTER=${AUTH_LDAP_FILTER}

