#!/usr/bin/with-contenv bash
source /default_vars.sh

[ -z "$USERNAME" ] && USERNAME="thehive"
[ -z "$GID" ] && GID=1000
[ -z "$UID" ] && UID=1000
CONFIG=${CONFIG:-"1"}

# Check if user must be created
if [ -n "$(id "$USERNAME" > /dev/null)" ]
then
    usermod -u "${UID}" "$USERNAME"
    groupmod -g "${GID}" "$USERNAME"
fi

chown -R "$USERNAME":"$USERNAME" "${DATA_PATH}" /opt/*
chgrp "$USERNAME" "$CONFIG_FILE"
chmod 640 "$CONFIG_FILE"

if [ "$CONFIG" -eq 1 ]
then

	sed -i "s/hosts:.*/hosts: [${AUTH_AD_HOSTS}]/g" "$CONFIG_FILE"
    #sed -i "s/\${??AUTH_LDAP_HOSTS}/${?AUTH_LDAP_HOSTS}/g" "$CONFIG_FILE"

fi

if [ $DEBUG ]
then
    sed -i "s/name=\"org.thp\" level=\"INFO\"/name=\"org.thp\" level=\"DEBUG\"/" "$LOGGER_FILE"
fi