#!/usr/bin/with-contenv bash
source /default_vars.sh

exec s6-setuidgid thehive \
/opt/thehive/bin/thehive \
	-Dconfig.file="$CONFIG_FILE" \
	-Dlogger.file=/etc/thehive/logback.xml \
	-Dpidfile.path=/dev/null \
	"$@"
	