#!/usr/bin/with-contenv sh
export CASSANDRA_DB_HOSTNAME=${CASSANDRA_DB_HOSTNAME:-"cassandra"}
export TH_CORTEX_URL=${TH_CORTEX_URL}
export TH_CORTEX_KEY=${TH_CORTEX_KEY}
export TH_MISP_URL=${TH_MISP_URL}
export TH_MISP_KEY=${TH_MISP_KEY}
export TH_MISP_CASE_TEMPLATE=${TH_MISP_CASE_TEMPLATE}
#export SECRET=${SECRET:-"$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)"}
export CONFIG_FILE=${CONFIG_FILE:-"/etc/thehive/application.conf"}

exec s6-setuidgid thehive \
/opt/thehive/bin/thehive \
	-Dconfig.file="$CONFIG_FILE" \
	-Dlogger.file=/etc/thehive/logback.xml \
	-Dpidfile.path=/dev/null \
	"$@"
	