#!/usr/bin/with-contenv sh
exec s6-setuidgid thehive \
/opt/thehive/bin/thehive \
	-Dconfig.file=/etc/thehive/application.conf \
	-Dlogger.file=/etc/thehive/logback.xml \
	-Dpidfile.path=/dev/null \
	"$@"