version: "3"
networks:
    traefik_internal:
        external: true
    
services:
    elasticsearch:
        image: itbgk/elasticsearch-oss:7.9.2
        environment: 
        #- "ES_JAVA_OPTS=-Xms512M -Xmx512M" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
        - path.repo=/backup
        volumes:
        - $PWD/../../BACKUP/opencti-elasticsearch:/backup
    opencti:
        #environment: 
        # - APP__BASE_PATH=${OPENCTI_BASE_PATH}
        # - PROVIDERS__LDAP__STRATEGY=LdapStrategy
        # - PROVIDERS__LDAP__CONFIG__URL=ldaps://mydc.limeo.org:629
        # - PROVIDERS__LDAP__CONFIG__BIND_DN=cn=Administrator,cn=Users,dc=limeo,dc=org
        # - PROVIDERS__LDAP__CONFIG__BIND_CREDENTIALS=XXXXXXXXXX
        # - PROVIDERS__LDAP__CONFIG__SEARCH_BASE=cn=Users,dc=limeo,dc=org
        # - PROVIDERS__LDAP__CONFIG__SEARCH_FILTER={{`(cn={{username}})`}}
        # - PROVIDERS__LDAP__CONFIG__MAIL_ATTRIBUTE=mail
        # - PROVIDERS__LDAP__CONFIG__ACCOUNT_ATTRIBUTE=givenName
        # - PROVIDERS__LDAP__CONFIG__ALLOW_SELF_SIGNED=true
        # - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
        #- APP__LOGS_LEVEL=debug
        volumes:
            - ${SSL_ROOT_CA}:/etc/ssl/certs/custom-root-ca.crt:ro
        networks: 
            traefik_internal:
            default:
        ports:
            - 127.0.0.1:50000:8080
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.opencti.rule=Host(`opencti.${FQDN}`)"
            - "traefik.http.routers.opencti.entrypoints=https"
            - "traefik.http.services.opencti.loadbalancer.server.port=8080"
    minio:
        ports:
            - 127.0.0.1:50001:9000
