name: Build TheHive4 Docker Container
on: 
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
env:
  MY_DOCKER_REPO: ${{ secrets.DOCKERHUB_ORG }}/thehive4
  MY_DOCKER_CONTEXT: ./.docker/thehive4
  MY_DOCKER_DOCKERFILE: Dockerfile
jobs:
  latest:
    strategy:
      matrix:
        VERSION: [4.1.3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Output git ref sha1
        id: git-sha
        run: echo "EXT_GIT_REF_SHA1=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ${{env.MY_DOCKER_REPO}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag: ${{ env.EXT_GIT_REF_SHA1 }}
          extra_args: |
            --digest-file=/dev/termination-log 
            --reproducible 
            --destination ${{env.MY_DOCKER_REPO}}:${{ matrix.VERSION }} 
            --build-arg VERSION=${{ matrix.VERSION }}
          path: ${{ env.MY_DOCKER_CONTEXT }}
          build_file: ${{ env.MY_DOCKER_DOCKERFILE }}
          tag_with_latest: true
          cache: true
          cache_registry: ${{ secrets.DOCKERHUB_ORG }}/cache
  other:
    strategy:
      matrix:
        VERSION: [4.1.2,4.1.1,4.0.5,4.0.4,4.0.3,4.0.2]
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Output git ref sha1
        id: git-sha
        run: echo "EXT_GIT_REF_SHA1=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ${{env.MY_DOCKER_REPO}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag: ${{ env.EXT_GIT_REF_SHA1 }}
          extra_args: |
            --digest-file=/dev/termination-log 
            --reproducible 
            --destination ${{env.MY_DOCKER_REPO}}:${{ matrix.VERSION }} 
            --build-arg VERSION=${{ matrix.VERSION }}
          path: ${{ env.MY_DOCKER_CONTEXT }}
          build_file: ${{ env.MY_DOCKER_DOCKERFILE }}
          tag_with_latest: false
          cache: true
          cache_registry: ${{ secrets.DOCKERHUB_ORG }}/cache
