name: Docker build
on: 
  push:
    branches:
    - master
  schedule:
    - cron:  '0 0 * * 0'
    - cron:  '0 0 * * 4'
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: 'MISP/misp-modules.git'
          ref: 'main'
      - name: Output git ref sha1
        id: git-sha
        #run: echo '::set-output name=GIT_REF::$(git rev-parse HEAD)'
        run: echo "EXT_GIT_REF_SHA1=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ${{ secrets.DOCKERHUB_ORG }}/misp-module
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          #tag: ${{ steps.git-sha.outputs.GIT_REF }}
          tag: $EXT_GIT_REF_SHA1
          extra_args: 
          #path: 
          build_file: docker/Dockerfile
          tag_with_latest: true
          cache: false
          cache_registry: ${{ secrets.DOCKERHUB_ORG }}/cache
