name: Build Cortex Docker Container
on: 
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
env:
  MY_DOCKER_CONTEXT: ./.docker/cortex
  MY_DOCKER_DOCKERFILE: Dockerfile
  DOCKERHUB_ORG: ${{ secrets.DOCKERHUB_ORG }}/cortex
jobs:
  latest:
    strategy:
      matrix:
        VERSION: [3.1.0]
        include:
          # includes a new variable of npm with a value of 2
          # for the matrix leg matching the os and version
          - REGISTRY: hub.docker.com
            MY_DOCKER_REPO: ${{ env.DOCKERHUB_ORG }}
            REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          - REGISTRY: quay.io
            MY_DOCKER_REPO: ${{ secrets.QUAY_ORG }}/cortex
            REGISTRY_USERNAME: ${{ secrets.QUAY_USERNAME }}
            REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Output git ref sha1
        id: git-sha
        run: echo "EXT_GIT_REF_SHA1=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ${{matrix.MY_DOCKER_REPO}}
          username: ${{ matrix.REGISTRY_USERNAME }}
          password: ${{ matrix.REGISTRY_PASSWORD }}
          tag: ${{ env.EXT_GIT_REF_SHA1 }}
          extra_args: |
            --digest-file=/dev/termination-log 
            --reproducible 
            --destination ${{matrix.MY_DOCKER_REPO}}:${{ matrix.VERSION }} 
            --build-arg VERSION=${{ matrix.VERSION }}-1
          path: ${{ env.MY_DOCKER_CONTEXT }}
          build_file: ${{ env.MY_DOCKER_DOCKERFILE }}
          tag_with_latest: true
          cache: true
          cache_registry: ${{ secrets.DOCKERHUB_ORG }}/cache
  other:
    strategy:
      matrix:
        VERSION: [3.0.0]
        include:
          # includes a new variable of npm with a value of 2
          # for the matrix leg matching the os and version
          - MY_DOCKER_REPO: ${{ secrets.DOCKERHUB_ORG }}/cortex
            REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          - MY_DOCKER_REPO: ${{ secrets.QUAY_ORG }}/cortex
            REGISTRY_USERNAME: ${{ secrets.QUAY_USERNAME }}
            REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Output git ref sha1
        id: git-sha
        run: echo "EXT_GIT_REF_SHA1=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ${{env.MY_DOCKER_REPO}}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
          tag: ${{ env.EXT_GIT_REF_SHA1 }}
          extra_args: --digest-file=/dev/termination-log --reproducible --destination ${{env.MY_DOCKER_REPO}}:${{ matrix.VERSION }} --build-arg VERSION=${{ matrix.VERSION }}-1
          path: ${{ env.MY_DOCKER_CONTEXT }}
          build_file: ${{ env.MY_DOCKER_DOCKERFILE }}
          tag_with_latest: false
          cache: true
          cache_registry: ${{ secrets.DOCKERHUB_ORG }}/cache
