name: Build TheHive Synapse Docker Container
on: 
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
env:
  MY_DOCKER_REPO: ${{ secrets.DOCKERHUB_ORG }}/thehive-synapse
  MY_DOCKER_CONTEXT: .
  MY_DOCKER_DOCKERFILE: Dockerfile
  #GIT_REPO: 'jeffrey-e/Synapse'
  GIT_REPO: '8ear/Synapse'
jobs:
  latest:
    strategy:
      matrix:
        VERSION: [master]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.GIT_REPO }}
          ref: '${{ matrix.VERSION}}'
      - name: Output git ref sha1
        id: git-sha
        run: echo "EXT_GIT_REF_SHA1=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ${{env.MY_DOCKER_REPO}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag: ${{ env.EXT_GIT_REF_SHA1 }}
          extra_args: |
            --digest-file=/dev/termination-log 
            --reproducible 
            --destination ${{env.MY_DOCKER_REPO}}:${{ matrix.VERSION }} 
            --build-arg VERSION=${{ matrix.VERSION }}-1
          path: ${{ env.MY_DOCKER_CONTEXT }}
          build_file: ${{ env.MY_DOCKER_DOCKERFILE }}
          tag_with_latest: true
          cache: true
          cache_registry: ${{ secrets.DOCKERHUB_ORG }}/cache
  # older:
  #   strategy:
  #     matrix:
  #       VERSION: [1.1.1]
  #   continue-on-error: true
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         repository: ${{ env.GIT_REPO }}
  #         ref: '${{ matrix.VERSION}}'
  #     - name: Output git ref sha1
  #       id: git-sha
  #       run: echo "EXT_GIT_REF_SHA1=$(git rev-parse HEAD)" >> $GITHUB_ENV
  #     - name: Kaniko build
  #       uses: aevea/action-kaniko@master
  #       with:
  #         image: ${{env.MY_DOCKER_REPO}}
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #         tag: ${{ env.EXT_GIT_REF_SHA1 }}
  #         extra_args: |
  #           --digest-file=/dev/termination-log 
  #           --reproducible 
  #           --destination ${{env.MY_DOCKER_REPO}}:${{ matrix.VERSION }} 
  #           --build-arg VERSION=${{ matrix.VERSION }}-1
  #         path: ${{ env.MY_DOCKER_CONTEXT }}
  #         build_file: ${{ env.MY_DOCKER_DOCKERFILE }}
  #         tag_with_latest: false
  #         cache: true
  #         cache_registry: ${{ secrets.DOCKERHUB_ORG }}/cache
