name: Build MISP Docker Container
on: 
  push:
    branches:
    - master
  schedule:
    - cron:  '0 0 * * 0'
    - cron:  '0 0 * * 4'
  workflow_dispatch:
jobs:
  v2.4.136:
    env: 2.4.136
      VERSION: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: 'MISP/MISP'
          ref: 'v${{ env.VERSION}}'
      - name: Output git ref sha1
        id: git-sha
        run: echo "EXT_GIT_REF_SHA1=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ${{ secrets.DOCKERHUB_ORG }}/misp-module
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag: ${{ env.EXT_GIT_REF_SHA1 }}
          extra_args: --digest-file=/dev/termination-log --reproducible --destination ${{ env.image }}/${{ env.VERSION }} --build-arg VERSION=${{ env.VERSION }}
          #path: 
          build_file: docker/Dockerfile
          tag_with_latest: true
          cache: true
          cache_registry: ${{ secrets.DOCKERHUB_ORG }}/cache
