name: Docker build
on: 
  push:
    branches:
    - master
  schedule:
    - cron:  '0 0 * * 0'
    - cron:  '0 0 * * 4'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: 'https://github.com/MISP/misp-modules.git'
          ref: 'master'
      - name: Output git ref sha1
        id: git-sha
        run: git rev-parse HEAD
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ${{ secrets.DOCKERHUB_ORG }}/misp-module
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag: ${{ steps.git-sha.outputs }}
          extra_args: 
          #path: 
          build_file: docker/Dockerfile
          tag_with_latest: true
          cache: false
          cache_registry: ${{ secrets.DOCKERHUB_ORG }}/cache
