# https://github.com/marketplace/actions/docker-lint
name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    # - name: lint
    #   uses: luke142367/Docker-Lint-Action@v1.0.0
    #   with:
    #     target: .docker/cortex/Dockerfile .docker/thehive4/Dockerfile
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker lint check
      uses: uditgaurav/docker-linter@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKERFILE: .docker/cortex/Dockerfile .docker/thehive4/Dockerfile