name: Sysdig CIS Benchmarks
on:
  pull_request:
    # paths: 
    #   - '.docker/**'
jobs:
  run:
    strategy:
      matrix:
        DIRECTORY: [.docker/cortex,.docker/thehive4]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Sysdig CIS Dockerfile Benchmark folder ${{ matrix.DIRECTORY }}
      uses: sysdiglabs/benchmark-dockerfile@v1.0.0
      with:
        directory: ${{ matrix.DIRECTORY }}
